# Generated by Django 3.2.1 on 2024-03-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedcsv',
            name='year_founded',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
